export const ENABLED_COMPONENTS = {
  cepWowFactor2: 'b2c_wowfactor',
  cepDescription: 'b2c_package_description',
  cepWhyWeLoveItTitle: 'b2c_why_we_love_it_title',
  cepWhyWeLoveItSubtitle: 'b2c_why_we_love_it_subtitle',
  cepWhyWeLoveItUSPs: 'b2c_why_we_love_it_list',
  cepHolidayInclusionGeneric: 'b2c_holiday_inclusion_generic',
  cepPkgImageGallery: 'b2c_main_gallery',
  packagePublishDate: 'b2c_package_publish_date',
  packageExpiryDate: 'b2c_package_expiry_date',
  travelStartDate: 'b2c_package_departure_start_date',
  travelEndDate: 'b2c_package_departure_end_date',
  termsConditions: 'b2c_terms_conditions',
  imageGalleryItem: 'b2c_main_gallery_image',
  consultantNotes: 'b2c_package_consultant_notes',
  valuedAtFlyStay: 'b2c_valued_at_flystay',
  valuedAtStay: 'b2c_valued_at_stay',
  basePriceFlyStay: 'b2c_base_price_flystay',
  basePriceStay: 'b2c_base_price_stay',
};
